const packages: any = [
  {
    id: "night-7",
    name: "7 Night Plans",
    duration: "7 Days",
    price: 50000,
    savings: 15,
    description: "Perfect for short getaways",
    avgPerNight: "₹7,143",
    features: [
      "Private room with daily breakfast",
      "₹3,000 food vouchers",
      "₹3,000 spa credit",
      "4 yoga sessions",
      "Access to all amenities including:",
      "Swimming pool",
      "Library",
      "Movie theatre",
      "Pool table",
    ],
  },
  {
    id: "night-14",
    name: "14 Night Plans",
    duration: "14 Days",
    price: 95000,
    savings: 20,
    description: "Perfect for longer renewal",
    avgPerNight: "₹6,786",
    features: [
      "Everything in 7-Night Plan, plus more:",
      "₹6,000 food vouchers",
      "₹6,000 spa credit",
      "Airport/Railway Pickup & Drop",
    ],
  },
  {
    id: "night-30",
    name: "30 Night Plans",
    duration: "30 Days",
    price: 170000,
    savings: 25,
    description: "Ideal for deep restoration",
    avgPerNight: "₹5,667",
    features: [
      "Everything in 14-Night Plan, plus more:",
      "₹6,000 food vouchers",
      "₹6,000 spa credit",
      "Airport/Railway Pickup & Drop",
    ],
  },
];

export const accomodation_data = {
  studio: {
    crest: {
      "7 Nights": {
        price: 47500,
        voucher: 6000,
        days: 7,
        description: "Perfect for short getaways",
        duration: "7 Days",
        orignal_per_night: 7500,
        avgPerNight: 6786,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹3,000",
          "Spa sessions: ₹3,000",
          "4 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "14 Nights": {
        price: 90000,
        days: 14,
        duration: "14 Days",
        description: "Perfect for longer renewal",
        voucher: 12000,
        orignal_per_night: 7500,
        avgPerNight: 6429,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹6,000",
          "Spa sessions: ₹6,000",
          "8 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "30 Nights": {
        price: 170000,
        days: 30,
        description: "Perfect for longer renewal",
        duration: "30 Days",

        orignal_per_night: 7500,
        voucher: 30000,
        avgPerNight: 5666,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹15,000",
          "Spa sessions: ₹15,000",
          "24 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
    },
    hamilton: {
      "7 Nights": {
        price: 50000,
        days: 7,
        description: "Perfect for short getaways",
        duration: "7 Days",
        voucher: 6000,
        orignal_per_night: 8000,
        avgPerNight: 7143,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹3,000",
          "Spa sessions: ₹3,000",
          "4 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "14 Nights": {
        days: 14,
        duration: "14 Days",
        description: "Perfect for longer renewal",
        price: 95000,
        orignal_per_night: 8000,
        voucher: 12000,
        avgPerNight: 6786,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹6,000",
          "Spa sessions: ₹6,000",
          "8 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "30 Nights": {
        days: 30,
        description: "Perfect for longer renewal",
        duration: "30 Days",

        price: 180000,
        orignal_per_night: 8000,
        voucher: 30000,
        avgPerNight: 6000,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹15,000",
          "Spa sessions: ₹15,000",
          "24 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
    },
    skyline: {
      "7 Nights": {
        days: 7,
        description: "Perfect for short getaways",
        duration: "7 Days",
        price: 55000,
        orignal_per_night: 8500,
        voucher: 6000,
        avgPerNight: 7857,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹3,000",
          "Spa sessions: ₹3,000",
          "4 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "14 Nights": {
        days: 14,
        duration: "14 Days",
        description: "Perfect for longer renewal",
        price: 100000,
        orignal_per_night: 8500,
        voucher: 12000,
        avgPerNight: 7142,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹6,000",
          "Spa sessions: ₹6,000",
          "8 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "30 Nights": {
        days: 30,
        description: "Perfect for longer renewal",
        duration: "30 Days",

        price: 190000,
        orignal_per_night: 8500,
        voucher: 30000,
        avgPerNight: 6333,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹15,000",
          "Spa sessions: ₹15,000",
          "24 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
    },
  },
  "1bhk": {
    regency: {
      "7 Nights": {
        days: 7,
        description: "Perfect for short getaways",
        duration: "7 Days",
        price: 65000,
        orignal_per_night: 10000,
        voucher: 6000,
        avgPerNight: 9286,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹3,000",
          "Spa sessions: ₹3,000",
          "4 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "14 Nights": {
        days: 14,
        duration: "14 Days",
        description: "Perfect for longer renewal",
        price: 125000,
        orignal_per_night: 10000,
        avgPerNight: 8929,
        voucher: 12000,

        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹6,000",
          "Spa sessions: ₹6,000",
          "8 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "30 Nights": {
        days: 30,
        description: "Perfect for longer renewal",
        duration: "30 Days",

        price: 220000,
        orignal_per_night: 10000,
        avgPerNight: 7333,
        voucher: 30000,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹15,000",
          "Spa sessions: ₹15,000",
          "24 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
    },
  },
  "2bhk": {
    victoria: {
      "7 Nights": {
        days: 7,
        description: "Perfect for short getaways",
        duration: "7 Days",
        price: 100000,
        orignal_per_night: 15000,
        voucher: 10000,
        avgPerNight: 14285,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹5,000",
          "Spa sessions: ₹5,000",
          "8 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "14 Nights": {
        days: 14,
        duration: "14 Days",
        description: "Perfect for longer renewal",
        price: 175000,
        orignal_per_night: 15000,
        voucher: 16000,
        avgPerNight: 12500,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹8,000",
          "Spa sessions: ₹8,000",
          "16 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "30 Nights": {
        days: 30,
        description: "Perfect for longer renewal",
        duration: "30 Days",

        price: 275000,
        orignal_per_night: 15000,
        avgPerNight: 9166,
        voucher: 36000,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹18,000",
          "Spa sessions: ₹18,000",
          "48 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
    },
    renaissance: {
      "7 Nights": {
        days: 7,
        description: "Perfect for short getaways",
        duration: "7 Days",
        price: 150000,
        orignal_per_night: 25000,
        avgPerNight: 21428,
        voucher: 12000,
        features: [
          "Room boarding with breakfast",
          "Food vouchers: ₹6,000",
          "Spa sessions: ₹6,000",
          "8 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "14 Nights": {
        days: 14,
        duration: "14 Days",
        description: "Perfect for longer renewal",
        price: 250000,
        orignal_per_night: 25000,
        voucher: 20000,
        avgPerNight: 17857,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: ₹10,000",
          "Spa sessions: ₹10,000",
          "16 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
      "30 Nights": {
        days: 30,
        description: "Perfect for longer renewal",
        duration: "30 Days",
        price: 360000,
        orignal_per_night: 25000,
        voucher: 40000,
        avgPerNight: 12000,
        features: [
          "Room boarding with breakfast",
          "Pick-up/drop from Airport or Railway",
          "Food vouchers: 20,000",
          "Spa sessions: ₹20,000",
          "48 Yoga sessions",
          "Access to swimming pool",
          "Access to movie theatre",
          "Access to library",
          "Access to pool table",
        ],
      },
    },
  },
};
